spring:
  application:
    name: node-diary
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    url: jdbc:mysql://localhost:3306/nodediary?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: nodediary
    password: Yyj20050204&
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: org.example.nodediary.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

