spring:
  application:
    name: node-diary
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  #本地Redis
  data:
    redis:
      host: 192.168.48.128
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  #  服务Redis
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      lettuce:
#        pool:
#          max-active: 10
#          max-idle: 10
#          min-idle: 1
#          time-between-eviction-runs: 10s
##服务端数据库
#  datasource:
#    url: jdbc:mysql://localhost:3306/nodediary?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    username: nodediary
#    password: Yyj20050204&
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  本地数据库
  datasource:
    url: jdbc:mysql://localhost:3306/nodediary?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Yyj20050204&
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: org.example.nodediary.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

